domits1/Domits

src/components/hostdashboard/Accommodations.js

temporary overview page and the right footer

for the main branch

---

src/components/hostdashboard/Accommodations.css
src/components/hostdashboard/Accommodations.js

added box-shadow: none;

---

src/components/assortment/Assortment.js
src/components/base/Header.js
src/components/base/base.css

The Log in screen close modal button text is now a x instead of 'Close Modal'. The close modal button no longer rotates when hovered.

Minor changes in the header

---

src/App.js
src/components/about/About.js
src/components/assortment/Assortment.js

Header is now visible on all pages because of a small fix in the header renderer in app.js. Deleted hardcoded header in Assortment.js.

Header visibility

---

src/components/base/base.css

cursor: pointer; toegevoegd aan: becomeAHost, nineDots, personalMenu waardoor je nu een hover over icon krijgt.

Quick fix: pointer

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/base/SearchResult.css
web/src/components/base/SearchResult.jsx
web/src/components/base/SearchResultsList.css
web/src/components/base/base.css

I fixed some bugs and visual issues with the search bar.

Final additions to the search 

---

app/Domits/ios/Domits.xcodeproj/project.pbxproj
app/Domits/ios/Domits/Info.plist

Small changes to build settings iOS.

iOS build settings changes

---

app/Domits/App.js
app/Domits/package-lock.json
app/Domits/package.json
app/Domits/src/navigation/appNavigation.js
app/Domits/src/screens/SearchBarApp.js
app/Domits/src/screens/homeScreen.js
package-lock.json
package.json

Kleine aanpassing van homepage en realiseren van de design die op figma staat

App Homepage

---

.idea/workspace.xml
app/Domits/App.js
app/Domits/src/components/BottomTabNavigator.js
app/Domits/src/navigation/appNavigation.js
app/Domits/src/screens/guestdashboard/guestDashboard.js
app/Domits/src/screens/homeScreen.js

BottomTabNavigator was incorrectly pushed so here it is, start for guest dashboard done

App navigation/guestdashboard

---

app/Domits/src/navigation/appNavigation.js
app/Domits/src/screens/bookingProcess.js
app/Domits/src/screens/homeScreen.js

Issue #235

---

web/src/components/base/Register.js

Added test for saving records in DynamoDB. Should be succesful but no way of checking as of now. Will continue tmrw

Added test for saving records in DynamoDB

---

app/Domits/src/header/header.js
app/Domits/src/screens/detailpage.js
app/Domits/src/screens/homeScreen.js

APP: bar visibility

---

.idea/workspace.xml
app/Domits/android/app/build.gradle
app/Domits/android/gradle.properties
app/Domits/src/screens/account.js
app/Domits/src/screens/guestdashboard/guestDashboard.js
app/Domits/src/screens/guestdashboard/helpAndFeedback.js
app/Domits/src/screens/guestdashboard/paymentMethods.js
app/Domits/src/screens/guestdashboard/profile.js
app/Domits/src/screens/guestdashboard/reviews.js
app/Domits/src/screens/guestdashboard/settings.js
app/Domits/src/screens/hostdashboard/dashboard.js
app/Domits/src/screens/hostdashboard/hostDashboard.js
app/Domits/src/screens/hostdashboard/listings.js
app/Domits/src/screens/hostdashboard/payments.js
app/Domits/src/screens/hostdashboard/profile.js
app/Domits/src/screens/hostdashboard/settings.js
app/Domits/src/screens/messages.js
package-lock.json

App SafeAreaView Implemented and correct build.gradle

---

web/public/index.html
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

Made some big improvments to the searchbar on the web. The autocomplete will only work with Countries and Cities and the styling have some smaller improvements :)

Changes to Search 

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

Web: Icons toegevoegd

---

web/package-lock.json
web/package.json
web/src/components/base/SearchBar.css
web/src/components/base/base.css

package fix

---

app/Domits/package-lock.json
app/Domits/package.json
app/Domits/src/screens/messages.js

install npm package react-native-gifted-chat

basic chat example

---

app/Domits/android/app/src/main/AndroidManifest.xml
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/base/base.css

Fixed the positionig of the searchbar. Before it it had fixed values, Thx Tim

WEB: changed the fixed values

---

app/Domits/src/navigation/appNavigation.js
app/Domits/src/screens/hostonboarding/LocationFillIn.js
app/Domits/src/screens/hostonboarding/selectAmenities.js

third page

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/base/base.css
web/src/components/contact/contact.css

changes to positioning of header components

Web: header

---

web/package-lock.json
web/src/App.css
web/src/components/hostdashboard/Accommodations.css
web/src/components/hostdashboard/Accommodations.js

Web search fix

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/base/base.css

`Description: Verbinding gemaakt met de database, api gateway en lambda werken wel maar nog niet compleet`
`Additional Info: [Add any additional …

connectie met database

---

web/src/components/listingdetails/ListingDetails.js
web/src/components/listingdetails/listingdetails.css

`Related Issue: #466 `
`Description: Removed Timo's Farm in listingdetails.js (commented out)`
`Additional Info: Please remove this branch`

Removed Timo's farm, some fixes to css

---

web/src/components/base/SearchBar.css
web/src/components/base/base.css
web/src/components/hostdashboard/Accommodations.css
web/src/components/hostdashboard/Accommodations.js

`Related Issue: no issue`
`Description: Temporary fix for search tablet/mobile view`
`Additional Info: [Add any …

Temporary fix for search tablet/mobile

---

web/src/FlowContext.js
web/src/components/base/Register.js

Related Issue
Related Issue: #[issue number] This change is necessary so that users who register as hosts also get this role saved in the database.
Type of change
Big change (300+ changes)
[x} Small change (Less than 300 changes)
NPM Packages changed
Proposed Changes
Description: Register component changed to allocate for possible host role saving in dynamoDB table "users" , FlowContext file changed to set isHost to false by default
@Mentions …

Changed register to allow for host role saving in database.

---

web/src/components/landingpage/Calculator.js
web/src/components/landingpage/landing.css

`Related Issue: No issue`
`Description: Best i could do for now for revenue tool frontend`
`Additional Info: …

revenue tool frontend fix

---

web/src/components/about/About.js
web/src/components/about/about.css
web/src/components/base/Footer.js
web/src/components/base/base.css
web/src/components/careers/Careers.js
web/src/components/careers/careers.css
web/src/components/contact/Contact.js
web/src/components/contact/contact.css

`Related Issue: No issue`
`Description: Fixed front-end on all existing static pages + footer`
`Additional …

Frontend fixes to following pages: About, Footer, Jobs, Contact

---

web/src/components/base/ConfirmRegister.js
web/src/components/base/Register.js

Register is working again!
- [ x] Small change (Less than 300 changes)
register component will give correct groupname according to account type.
Please select if you want to keep the branch …

Register fixed to work with Host role.

---

web/src/components/base/Header.js
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/base/base.css
web/src/index.css

`Related Issue: No issue`
`Description: Fixed header/search on desktop. We need to take a look for responsiveness`
Include any additional information or context that might be necessary for understanding the pull …

Web header fefix

---

web/src/components/landingpage/OnboardingHost.js
web/src/components/landingpage/data/MapComponent.js
web/src/components/landingpage/landing.css

`Description: Gewerkt aan de onboarding host`
`Reviewer(s): @SHvanderWilt`
`Additional Info: Ik had op het …

Host onboarding

---

web/src/App.js
web/src/components/about/Helpdesk.js
web/src/components/about/Howitworks.js
web/src/components/base/Footer.js

- [ x] Small change (Less than 300 changes)
`Reviewer(s): @SHvanderWilt @Timmhart `
Include any additional information or …

Staticpages aangemaakt

---

web/src/components/about/Helpdesk.js
web/src/components/about/helpdesk.css
web/src/components/landingpage/Faq.css
web/src/components/landingpage/Faq.js
web/src/components/landingpage/landing.css

Helpdesk page eerste versie gemaakt met FAQ met content

---

web/package-lock.json
web/package.json
web/src/components/assortment/assortment.css
web/src/components/hostdashboard/Calendar.js
web/src/components/hostdashboard/HostCalendar.js
web/src/components/hostdashboard/HostHomepage.css

`Description: Een kalender toegevoegd aan de host dashboard`
`Additional Info: …

Host dashboard

---

web/cypress/TestWebsite.cy.js
web/package-lock.json
web/package.json
web/src/App.js
web/src/components/assortment/Assortment.js
web/src/components/base/Header.js
web/src/components/base/SearchBar.jsx
web/src/components/base/base.css
web/src/components/hostdashboard/Accommodations.js

`Description: [The most changes are in the back-end but the dropdown menu on the searchbar is now fully dynamic and functional. By selecting a type of accommendations you will get the right results and it wil automaticlly update on the homepage. In addition i cleaned up some unused code it wont effect anything]`
Mention the person or team responsible for reviewing the proposed changes. This notifies them that …

Aws search3

---

web/src/components/landingpage/OnboardingHost.js
web/src/components/landingpage/landing.css

`Related Issue: #[453]`
- [x ] Small change (Less than 300 changes)
`Description: Images optie toegevoegd`
`Reviewer(s): @SHvanderWilt @Timmhart `
Include any additional information or context that might be necessary for …

Onboarding images option

---

web/src/App.js
web/src/HostProtectedRoute.js
web/src/UserContext.js
web/src/components/hostdashboard/Pages.js

`Related Issue: #[402]`
`Description: [Added two files, UserContext and HostProtectedRoute. Made changes to pages.js and app.js to accommodate the new files. These files including the changes to the existing files make it so that the website only allows you to enter the host dashboard page if you are actually a Host by role. This is done by using react context, checking whether the current user has group:Host in cognito and allowing them to …

Host dashboard accessibility

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

`Description: [Made some improvments to the seachbar it should look look nicer]`
Include any additional information or context that might be necessary for understanding the pull …

web: Some changes to css of SearchBar

---

web/src/components/listingdetails/ListingDetails.js
web/src/components/listingdetails/ListingDetailsOud.js

Geen template??
Alle oude code even in een aparte file gezet gelieve deze niet te removen.

Web fefix listingdetails

---

amplify/#current-cloud-backend/amplify-meta.json
amplify/#current-cloud-backend/api/domits/build/cloudformation-template.json
amplify/#current-cloud-backend/api/domits/build/parameters.json
amplify/#current-cloud-backend/api/domits/build/schema.graphql
amplify/#current-cloud-backend/api/domits/schema.graphql
amplify/#current-cloud-backend/auth/domits7b73f586/build/auth-trigger-cloudformation-template.json
amplify/#current-cloud-backend/awscloudformation/build/api/domits/build/cloudformation-template.json
amplify/#current-cloud-backend/awscloudformation/build/awscloudformation/build/root-cloudformation-stack.json
amplify/#current-cloud-backend/awscloudformation/build/root-cloudformation-stack.json
amplify/backend/amplify-meta.json
amplify/backend/api/domits/build/cloudformation-template.json
amplify/backend/api/domits/build/parameters.json
amplify/backend/api/domits/schema.graphql
amplify/backend/auth/domits7b73f586/build/auth-trigger-cloudformation-template.json
amplify/backend/awscloudformation/build/api/domits/build/cloudformation-template.json
amplify/backend/awscloudformation/build/awscloudformation/build/root-cloudformation-stack.json
amplify/backend/awscloudformation/build/root-cloudformation-stack.json
src/graphql/mutations.js
src/graphql/queries.js
src/graphql/subscriptions.js
web/amplify/backend/api/domits/schema.graphql
web/src/App.js
web/src/components/chat/Chatprototype.js
web/src/components/details/Details.js
web/src/components/details/details.css
web/src/components/guestdashboard/Pages.js
web/src/components/hostdashboard/Pages.js

`Related Issue: #[#144 ]`
a url based system allowing users to start chats from other pages
these changes introduce a way for users to start chats from other pages by redirecting them to the chat with the recipient being correctly selected. furthermore, users can still be selected from the list of users within the chat component
`Reviewer(s): @SHvanderWilt 
Please select if you want to keep the branch you worked on, or have it …

chat url based

---

web/src/components/hostdashboard/Pages.js

`Related Issue: #402 `
`Description: Host accounts on dashboard now have a go to dashboard button instead of set up payments.

Hosts that already have a stripe account can now go to their stripe dashboard.

---

web/src/components/base/Footer.js

`Description: Domits logo in footer is now the appropiate size

Footer Domits logo is back to normal width

---

web/src/components/base/Register.js
web/src/components/hostdashboard/Pages.js

`Description: Pages.js in hostdashboard and CheckIfStripeExists lambda functions changed to accommodate for Stripe API usage in order to make a login link for the user.
`Additional Info: …

Host dashboard stripe button optimized to use stripe API

---

web/src/components/base/SkeletonLoader.css
web/src/components/base/SkeletonLoader.js
web/src/components/hostdashboard/Accommodations.css
web/src/components/hostdashboard/Accommodations.js

Revert "Skeleton loader toegevoegd"

---

web/src/components/base/Header.js

`Related Issue: #402 
`Description: Header component adjusted, now hosts can go to dashboard and then switch between the two. Users who arent logged in yet will not see a go to dashboard button but rather the Become a Host button that sends them to the register page.
Include any additional information or context that might be …

Hosts kunnen nu tussen twee dashboards switchen.

---

web/cypress.config.js
web/cypress/TestWebsite.cy.js
web/cypress/e2e/TestDates.cy.js
web/cypress/e2e/TestGuestDropDown.cy.js
web/cypress/e2e/TestLocation.cy.js
web/cypress/e2e/TestWebsite.cy.js

`Description: [I made some scripts to test searchbar on the website by using cypress]`

Scripts to test searchbar

---

web/src/components/landingpage/OnboardingHost.js

`Description: Kleine foutmelding gefixed`

Onboarding foutmelding gefixed

---

web/src/components/base/Register.js

`Description: Register.js aangepast zodat gebruikers gewoon tijdens registratie een checkbox kunnen gebruiken om een host te worden.
`Additional Info: [Add any additional information …

Knop in register om Host te kunnen worden.

---

web/cypress/e2e/HomePage.cy.js

`Description: Small fix for HomePage cypress test`

HomePage test fixed

---

web/package-lock.json
web/package.json
web/src/components/landingpage/OnboardingHost.js

`Description: Belangrijke merge`

Images gefixed en critical vulnerability weggehaald

---

web/package-lock.json
web/package.json

`Description: gh package verwijderd. Onnodige package dat niet noodzakelijk is voor onze website: https://www.npmjs.com/package/gh`
`Reviewer(s):  @roberthopman @iLLy-27 `
`Additional Info: [Add any additional information …

Veeeel vulnerabilities weg gehaald

---

app/Domits/src/screens/account.js
web/src/components/guestdashboard/Pages.js

`Description: "Payments" tab weg van guestdashboard.

Payments tab voorlopig weg van guestdashboard.

---

web/src/components/hostdashboard/HostHomepage.css
web/src/components/hostdashboard/HostListings.js
web/src/components/utils/PageSwitcher.css
web/src/components/utils/PageSwitcher.js

`Description: 
- Listed accommodations can be removed on demand of the host
- Listing can be refreshed`

HostListing deletion and styling optimization

---

web/package-lock.json

`Name: @ChahidLaaouar `
`Description: nth-check package veranderd naar een nieuwere versie`
`Reviewer(s): @roberthopman @SHvanderWilt `

Nog meer vulnerabilities weg gehaald

---

web/cypress/e2e/Hostdashboard.cy.js
web/cypress/e2e/TravellerDashboard.cy.js
web/src/components/__tests__/Footer.test.js
web/src/components/__tests__/Header.test.js
web/src/components/__tests__/Login.test.js

- [] Small change (less than 300)
`Description: I removed some old jest tests that were giving errors in de action for now, they can be used later. I made two tests of login, chat and enlist
Include any additional information or context that …

Removed old jets test (for now) And added tests voor de chat and enlist

---

app/Domits/package-lock.json
app/Domits/package.json

`Description: Amplify npm package added.

Amplify package installed

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

`Description: performance optimalisations, results should appear instantly`

performance optimalisations

---

web/cypress/e2e/TestDates.cy.js
web/public/index.html
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/home/Accommodations.js

`Description:  Optimalisatie/ fixing error in console, added async for placeautocomplete for faster response and removed unused code.` …

Optimalisatie/ fixing error in console

---

app/Domits/package-lock.json
app/Domits/src/screens/login/loginScreen.js

safeareaview toegepast en alerts op niet bestaande knoppen …

kleine aanpassing aan loginscreen.js

---

web/cypress/e2e/TravellerDashboard.cy.js
web/public/index.html
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/home/Accommodations.js

`Description: Removed unused code and small adjustments`

Removed unused code and small adjustments

---

web/src/components/guestdashboard/guestdashboard.css
web/src/components/hostdashboard/HostCalendar.js
web/src/components/hostdashboard/HostHomepage.css

`Description: Improved responsive styling of Host Calendar and reviews page`
`Additional Info: [Add any additional information …

Improved Hostdashboard responsive styling

---

web/src/components/base/Register.css
web/src/components/base/Register.js

`Description: [**Added an error message for to short username and to short password**]`
`Additional Info: [Add any additional …

Added an error message for to short username and to short password

---

web/package-lock.json
web/package.json
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

`Description: New look for the calendar part in the searchbar. New packages are @hassanmojab/react-modern-calendar-datepicker and deleted are react-datepicker`
Include any additional information or context that might be necessary for …

New look for the calendar part in the searchbar

---

web/src/components/guestdashboard/guestdashboard.css
web/src/components/hostdashboard/HostDashboard.js
web/src/components/hostdashboard/HostHomepage.css
web/src/components/hostdashboard/HostReviews.js

`Description:
Improved the overall responsiveness of host dashboard (home)
Fixed a problem where text were uncentered after pulling origin acceptance`
Include any additional information or context that might be necessary for understanding the pull …

Improved host dashboard responsiveness

---

app/Domits/package-lock.json
app/Domits/package.json
app/Domits/src/screens/login/loginScreen.js

Amplify aanpassingen

---

web/cypress/e2e/Hostdashboard.cy.js
web/cypress/e2e/TestDates.cy.js
web/cypress/e2e/TestWebsite.cy.js
web/src/components/base/Register.js
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

Not yet i need those for now but when its finished i will removed them
(Important) Without a Jest test, your pull …

Search mobile responsive + fixed failed tests + Added function to search on guests

---

web/cypress/e2e/TestLocation.cy.js
web/cypress/e2e/TestWebsite.cy.js
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

Fixed faild tests

---

web/src/components/landingpage/OnboardingHost.js
web/src/components/landingpage/onboardingHost.css

`Related Issue: #499 `
`Description: Uploaded images seem to disappear after refreshing the browser, this issue is now fixed.` …

Fixed image upload to S3

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

fixes to mobileview of searchbar ( Accommodations still need some work)

---

web/src/components/hostdashboard/HostDashboard.js
web/src/components/hostdashboard/HostHomepage.css
web/src/components/hostdashboard/Pages.js

`Description: 
Implemented new design of host dashboard:
- Listed 3 most recent accommodation owned by the host
- Copied host settings to dashboard
- Added multiple new tabs according to the new design on figma
- Resized the tabs so more of them can fit in one screen`
(Important) …

Host dashboard new design

---

web/cypress/e2e/TestWebsite.cy.js
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

`Description: [Added error message if there are no results found and restructured the jsx part to make the message work]`
(Important) Frontend and back-end must be split before your …

Added error message if there are no results found

---

web/src/components/listingdetails/ImageGallery.js
web/src/components/listingdetails/ListingDetails.js
web/src/components/listingdetails/imagegallery.css
web/src/components/listingdetails/listing.css

Listing details

---

web/src/components/base/ConfirmRegister.js
web/src/components/base/Header.js
web/src/components/base/Register.js

`Related Issue: #707 
`Description: Header, register, confirmregister all changed to accommodate for new, useful functions. The become a host button now checks the users role and acts accordingly
(Important) Frontend and …

Web: added functionalities for Become a Host button to work better

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

`Description: [de titles die zeggen wat elke hokje is , is nu placeholders geworden]` …

Titles -> placeholder in searchbar

---

web/src/components/base/Footer.js
web/src/components/base/Login.js
web/src/components/checkout/CheckoutFrontEnd.js

Footer bijgewerkt, bezig met login sturen naar dashboard

---

web/src/components/base/Header.js
web/src/components/landingpage/Landing.js
web/src/components/landingpage/landing.css

`Related Issue: #771 
`Description: Landing.js is halfway done being edited according to the Figma Design.
(Important) Without a …

Web: Landing page halverwege vernieuwing

---

web/src/components/landingpage/OnboardingHost.js

`Description: Jiaming en ik hebben aanpassingen toegebracht aan de functie verantwoordelijk voor het opslaan van images in de database`
(Important) Frontend and back-end must be split …

Enlist code aanpassingen (images)

---

web/package-lock.json
web/package.json
web/src/components/base/SearchBar.jsx

…ation
`Description: [Routing function so that you can use search no matter the location. The users data will also tranfser. So when you are not in the homepage and you try to search for something you will be redirected to the homepage and then the users input will be exected.]` …

Routing function so that you can use search no matter the location

---

web/src/App.js
web/src/components/landingpage/OnboardingHost.js
web/src/components/landingpage/landing.css
web/src/components/landingpage/onboardingHost.css
web/src/components/listingdetails/ListingDetails.js
web/src/components/listingdetails/bookingdetails.js

`Description: Implemented new design of enlist, fixed bug for listingdetails where dates can't be chosen when the start date of an accommodation is later than today`
(Important) Frontend and …

Host onboarding new design and bug fixed

---

web/package-lock.json
web/src/App.js
web/src/components/ScrollToTop/ScrollToTop.tsx

`Name: @Danivdmijl `
- [] Small change (less than 300)
- [V] Did you check for vulnerabilities using "npm audit"?
`Description: [I updated the app.js importing a new file called ScrollToTop I also made a folder ScrollToTop inside the components folder inside the ScrollToTop is a tsx file named ScrollToTop that gets imported in the app,js so that everypage when landing is at the top`
- [V] Console.logs are deleted
- [V] Comments are deleted (or not used).
(Important) …

ScrollToTop Function added all pages

---

web/cypress/e2e/Auth.cy.js
web/cypress/e2e/TravellerDashboard.cy.js
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

`Description: [fixed the cypress tests and fixed some front-end sided with seach. The mobileview should look a bit better and replaced some placeholders and fontsizes]`
(Important) …

fixed the cypress tests and fixed some front-end sided with seach

---

web/src/components/__tests__/searchBar.test.js
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

fiexed the jest test for search

---

web/src/components/base/Header.js
web/src/components/landingpage/OnboardingHost.js

`Description: OnboarrdingHost.js fixed so that you dont have to change things in order to enlist …

Web: enlist fixed, price now has default value

---

web/cypress/support/commands.js
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

fixed the cypress test for messages

---

web/src/components/__tests__/HostDashboard.test.js
web/src/components/hostdashboard/HostDashboard.js

`Name: @SHvanderWilt `
`Related Issue: #88 `
`Description: Added a new test for the hostdashboard, and made a small change to the hostdashboard because of the test results`

Jest testing (Hostdashboard)

---

web/src/components/booking/BookingOverview.js

consile.log snel weggehaald

---

web/src/components/booking/BookingOverview.js

Stripe prijs gefixed

---

web/src/components/__tests__/pageNotFound.test.js
web/src/components/error/404NotFound.js
web/src/components/error/error.css

`Related Issue: #837 `
`Additional Info: Adjusted css styling which affected the layout of Host Dashboard and created new jest test for 404 not found page`

Styling fix and Jest test for 404 not found page

---

.idea/workspace.xml
app/Domits/src/screens/messages.js
app/Domits/src/screens/subscriptions.js

`Name: @nNab1l `
`Related Issue: #562 `
`Description: notifications from web implemented to the app. styling to be added`
`Reviewer(s): @Hamzatjo `

chat app notifications

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

`Description: [Input of the user will be exected automaticly, the search results also appear almost instant and it works with the navigate function.]`

Big optimalisation changes for the search

---

web/cypress/e2e/TestWebsite.cy.js
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

`Description: [fixed the error message while typing]`

Cache function

---

web/src/components/booking/BookingOverview.js
web/src/components/booking/PaymentConfirm.js
web/src/components/guestdashboard/GuestBooking.js
web/src/components/guestdashboard/guestdashboard.css
web/src/components/guestdashboard/paymentsguestdashboard.css
web/src/components/hostdashboard/Hostchat.js

Booking engine

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

Small css changes

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

position change of the placeholder

---

web/src/components/home/Accommodations.js
web/src/components/landingpage/OnboardingHost.js

`Name: @iLLy-27 @ChahidLaaouar `
`Related Issue: #865`
`Description: Accommodations can be marked as 'drafted' and they will not be shown on the listings when created, when the host does not have a Stripe account or the accommodations does not have a date range, the accommodation is marked as draft by default.`

Drafted Accommodations

---

web/src/components/booking/BookingOverview.js
web/src/components/booking/PaymentConfirm.js

`Description: Drafted (niet af gemaakte) accommodaties zijn niet zichtbaar omdat dit een paar problemen veroorzaakt`

Geef alleen enlisted booking weer

---

web/src/components/booking/BookingOverview.js

Stripe live

---

web/cypress/e2e/TestWebsite.cy.js
web/cypress/e2e/TravellerDashboard.cy.js
web/cypress/e2e/messagesTab.cy.js
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

`Description: [I saw that some cypress tests are failing again so i fix those]`

Fixes to tests so that they wont fail anymore

---

web/src/components/landingpage/OnboardingHost.js

Added Boat and Camper as new types of accommodation

---

web/public/index.html
web/src/components/base/SearchBar.jsx

`Description: [Added new api key voor placesautocomplete because the old one didn't work, now it works! . And small restructure of seach; deleted old and unused code.]`

New google api key for placesautocomplete, small improvments to search

---

web/src/App.js
web/src/components/chatbot/chatbot.css
web/src/components/chatbot/chatbot.js

fixed css conflict file

---

web/src/components/landingpage/OnboardingHost.js

`Description: onboardinghost.js changed

Enlist price slider fixed

---

web/src/components/base/base.css
web/src/components/booking/BookingOverview.js
web/src/components/booking/ListingDetails.js
web/src/components/hostdashboard/StripeModal.js
web/src/components/hostdashboard/StripeModal.module.css

Price and fee overview fixed. Stripe notification on dashboard optimized

---

web/src/components/booking/ListingDetails.js

`Description: Listingdetails fixed so that only the available amenities are shown.

Web: listingdetails amenities fixed

---

package-lock.json
package.json
web/src/App.js
web/src/components/about/Whydomitstwo.js
web/src/components/about/howitworksrework.css
web/src/components/about/whydomits.css

`Name: @Danivdmijl `
`Related Issue: #685 `
`Description: [Added WhyDomitsPage and made responsive + fixed small responsive changes Howitworks page]`
`Reviewer(s): @TimSeijlhouwer `

Responsive Page made/ added #685 and small change HowItWorks Page 

---

web/src/components/guestdashboard/GuestBooking.js
web/src/components/landingpage/OnboardingHost.js

`Description: GuestBookings euro symbol added. OnboardingHost cleaning fee added (front-end only)

Web: cleaning fee added to front-end, guestpayments optimized

---

web/src/components/booking/BookingOverview.js
web/src/components/booking/ListingDetails.js

`Description: ListingDetails.js, BookingOverview.js and the CreateStripeCheckout lambda function adjusted for the price to be calculated better.

Payment rounding issue resolved (hopefully)

---

web/src/App.js
web/src/components/about/About.js
web/src/components/about/about.css
web/src/components/about/datasafety.css
web/src/components/about/datasafety.js

`Name: @Danivdmijl `
`Related Issue: #740 #735 `
`Description: Added About + Data Safety page and made the pages responsive
`Reviewer(s): @TimSeijlhouwer `

Created pages #735 #740

---

web/src/components/base/Header.js

Header.js navbar dynamic

---

web/src/components/home/Accommodations.css
web/src/components/home/Accommodations.js
web/src/components/hostdashboard/HostHomepage.css

Web: homepage responsiveness adjusted

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/base/base.css

`Description: [Now in mobile view you have a button to open the search menu so that it wont automaticly take a lot of space when you dont need it ]`

Added more optimization to search in mobile view

---

web/src/components/booking/BookingOverview.js
web/src/components/booking/bookingoverview.css

Bookingoverview small adjustments

---

web/src/components/landingpage/OnboardingHost.js

`Description: OnboardingHost component had a flaw in handling loading states. Fixed after thorough research.

Onboarding Host fix

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

Placeholder position fix mobile-view

---

web/src/components/booking/BookingOverview.js
web/src/components/hostdashboard/Pages.js

`Related Issue: #898 #899 `
`Description:
- Added a button for hosts to add accommodations via the sidenav
- Booking requests are set to Accepted when the payment is successful`

Quick fixes and optimalizations for Booking and HostDashboard

---

web/src/components/booking/BookingOverview.js
web/src/components/booking/ListingDetails.js
web/src/components/booking/listing.css
web/src/components/hostdashboard/HostCalendar.js
web/src/components/hostdashboard/HostHomepage.css
web/src/components/utils/ReservationItem.js

web: css fixes and rounding in host reservations

---

web/src/components/booking/BookingOverview.js
web/src/components/booking/ListingDetails.js

Web: cleaning fee integrated to both front-end and payment

---

web/src/components/landingpage/Faq.css
web/src/components/landingpage/Faq.js

Web: FAQ optimizations, additions

---

web/src/components/booking/ListingDetails.js
web/src/components/landingpage/Faq.js

`Related Issue: #928 
`Description: Faq.js in components/landingpage expanded to accommodate for the desired questions found in the document in the related issue

Web: FAQ for Host expanded

---

web/src/components/hostdashboard/HostPayments.js
web/src/components/hostdashboard/HostReports.css

`Description: HostPayments.js and HostReports.css adjusted so that the page looks better and the content is not overlapping or too close to eachother

Web: host reporting page CSS fixed

---

web/public/index.html

placesautocomplete gebruikt defer async ( KAN MOGELIJK NIET WERKEN OP PRODUCTIE )

---

web/public/index.html

Revert "placesautocomplete gebruikt defer async ( KAN MOGELIJK NIET WERKEN OP PRODUCTIE )"

---

web/src/components/landingpage/Faq.js

`Related Issue: #928 
`Description: Faq.js expanded with the items in the document listed in the issue.

Web: FAQ Guest expanded as per issue #928

---

web/src/components/hostdashboard/HostPayments.js
web/src/components/hostdashboard/HostReports.css

`Description: HostPayments.js and HostReports.css adjusted for a better looking front-end.

Web: HostPayments CSS fixes

---

web/.gitignore
web/package-lock.json
web/package.json
web/public/index.html
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/base/base.css

De Google apikey wordt nu dynamisch geladen in plaats van hardcoded

---

web/src/components/booking/ListingDetails.js
web/src/components/guestdashboard/GuestDashboard.js
web/src/components/guestdashboard/guestdashboard.css

Web: small guestdashboard CSS fixes

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

nieuwe URLSEARCHPARAMS in plaats van filter(Boolean)

---

web/src/components/base/SearchBar.jsx

loading = async url

---

web/src/components/base/Header.js
web/src/components/contact/Contact.js

Web: messages button in dropdown header fixed.

---

web/src/components/guestdashboard/GuestSettings.js
web/src/components/guestdashboard/Pages.js
web/src/components/guestdashboard/guestdashboard.css
web/src/components/hostdashboard/HostHomepage.css
web/src/components/hostdashboard/Pages.js

`Description: Bij beide dashboards worden de knoppen links groen en de text ervan wit wanneer je op de pagina zit van die tab

Web: dasbhoard navbars green buttons when clicked

---

web/src/components/booking/ListingDetails.js
web/src/components/booking/listing.css
web/src/components/landingpage/OnboardingHost.js
web/src/components/landingpage/onboardingHost.css

`Name: @iLLy-27`
`Related Issue: -`
`Description: Fixed icons not displaying properly on the listing detail page and categorized checkboxes for enlist`

Improved amenity icons for bookingengine and categorized checkboxes for enlist

---

web/src/components/guestdashboard/guestdashboard.css
web/src/components/hostdashboard/HostHomepage.css

Guestdashboard navbar fixed.

---

web/src/components/chatbot/chatbot.js
web/src/components/chatwidget/ChatWidget.js

`Name: @Electroviz `
`Related Issue: #443 `

fixed links

---

web/src/components/hostdashboard/CalendarComponent.js
web/src/components/landingpage/OnboardingHost.js

`Description: Fixed bug where user has to select the same date range twice to take effect`

Host onboarding calendar fix

---

web/src/components/hostdashboard/HostHomepage.css
web/src/components/hostdashboard/HostListings.js
web/src/components/utils/PageSwitcher.js

`Related Issue: `
`Description: Adjusted the PageSwitcher component to use DateRanges instead of start date and end date, this is because the accommodations in HostListings were not displaying the dates correctly.`
`Reviewer(s): @iLLy-27 `

Bug fixes: Drafted accommodations cannot be set live

---

web/package-lock.json
web/src/App.css
web/src/components/about/about.css
web/src/components/about/howitworksrework.css
web/src/components/about/release.css
web/src/components/about/whydomits.css
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/base/base.css
web/src/components/booking/ListingDetails.js
web/src/components/booking/listing.css
web/src/components/careers/careers.css
web/src/components/chatwidget/ChatWidget.css
web/src/components/home/Accommodations.css
web/src/components/landingpage/Faq.css
web/src/components/landingpage/Faq.js

`Name: @Timmhart `
`Related Issue: No issue attached`
`Description: Changed a few faq questions and answers, and a lot of styling to different pages.`

Faq questions/answers and styling changes

---

web/src/components/base/Header.js
web/src/components/booking/ListingDetails.js
web/src/components/booking/listing.css
web/src/components/chat/chat.css
web/src/components/hostdashboard/Hostchat.js

`Related Issue: No issue related`
`Description: Added contact list (unfinished) for hostdashboard`
`Reviewer(s): @iLLy-27 `

Contact list prototype

---

web/src/App.css
web/src/components/about/helpdesk.css
web/src/components/base/base.css
web/src/components/booking/BookingCalendar.module.css
web/src/components/booking/listing.css
web/src/components/contact/contact.css
web/src/components/guestdashboard/settingsguestdashboard.css
web/src/components/home/Accommodations.css
web/src/components/hostdashboard/Calendar.module.css
web/src/components/hostdashboard/HostHomepage.css
web/src/components/hostdashboard/HostReports.css
web/src/components/hostdashboard/HostRevenueStyle.css
web/src/components/landingpage/Faq.css
web/src/components/ninedots/ninedots.css

ChatGPT Comments clean up + unused css deleted

---

web/src/App.js
web/src/components/base/Header.js
web/src/components/base/MenuBar.css
web/src/components/base/MenuBar.js
web/src/components/base/SearchBar.jsx
web/src/components/base/base.css
web/src/components/chatwidget/ChatWidget.css
web/src/images/arrow-up-icon.svg

`Name: @Chanlyj `
`Related Issue: #[996]`
`Description: [Created an extra component in order to get the "Become a host", "9 dots" and "login/register" at the bottom of the screen for mobile view]`
`Reviewer(s): @iLLy-27  `

Medium fix: Navigation: Header responsive #996

---

package-lock.json
web/src/components/about/Helpdesk.js
web/src/components/about/helpdesk.css
web/src/components/base/Login.css
web/src/components/base/Login.js
web/src/components/base/Register.css
web/src/components/booking/listing.css
web/src/components/landingpage/Faq.css
web/src/components/landingpage/Faq.js

`Name: @Timmhart `
`Related Issue: No issue connected.`
`Description: Styling changes and added working search feature to helpdesk page (faq items) You can search now on heading, questions and answers.`
`Reviewer(s): @iLLy-27 `

Added styling changes to several pages + added working search feature to helpdesk faq items.

---

web/src/components/base/Header.js
web/src/components/base/MenuBar.js
web/src/components/base/Register.js
web/src/components/guestdashboard/GuestDashboard.js
web/src/components/guestdashboard/GuestSettings.js
web/src/components/hostdashboard/HostDashboard.js
web/src/components/hostdashboard/HostSettings.js
web/src/components/review/ReviewPage.js

register has two new fields first name and last name.

Register first last name

---

web/cypress/e2e/Auth.cy.js
web/cypress/e2e/TestHeader.cy.js
web/cypress/e2e/TestHostCalendar.cy.js
web/cypress/e2e/TestHostDistribution.cy.js
web/cypress/e2e/TestHostIoTHub.cy.js
web/cypress/e2e/TestHostMonitoring.cy.js
web/cypress/e2e/TestHostOccupancy.cy.js
web/cypress/e2e/TestHostPricing.cy.js
web/cypress/e2e/TestHostPromocodes.cy.js
web/cypress/e2e/TestHostReservations.cy.js
web/cypress/e2e/TestHostRevenues.cy.js
web/cypress/e2e/TestHostScreening.cy.js
web/cypress/e2e/TestHostSetup.cy.js
web/src/components/base/Header.js

`Related Issue: No issues related`
`Description: Attempted to fix failing Cypress test`
`Reviewer(s): @iLLy-27  `

Fixed failing Cypress tests

---

web/src/components/booking/ListingDetails.js
web/src/components/booking/listing.css

`Name: @Santoshskk `
`Related Issue: #1037 `
`Description: I changed the design and structure of the left side of the page. I also added a pop up that shows the amenities instead of a dropdown. I added break lines to make the overview clearer`
`Reviewer(s): @ `

Features of a room popup

---

web/src/components/careers/jobDetails.js
web/src/components/careers/jobs.json

Revamp careers. First example.

---

web/src/components/about/howitworksrework.css

`Name: @2174951 `
`Description: [Updated the How-it-works page to make it responsive]`

How-it-works page update (responsive)

---

web/src/components/careers/jobs.json

Tim careers

---

web/src/components/landingpage/Faq.js

`Name: @Chanlyj `
`Related Issue: #1011 `
`Description: [Buttons on helpdesk redirect to corresponding helpdesk (host to /helpdesk-host and guest to /helpdesk-guest)]`

Helpdesk: Correct url #1011

---

web/src/components/landingpage/Landing.js
web/src/components/landingpage/landing.module.css

`Name: @2174951 `
`Description: Added functionality to the "start hosting" button and made changes to make it more mobile responsive`

Landing page adjustments

---

web/src/components/landingpage/OnboardingHost.js

Changed first "Beds" to "Bedrooms" in onboarding host step

---

web/src/components/hostdashboard/HostReservations.js

`Name: @chantbalci `
`Related Issue: #[1077]`
`Description: The "All" button is dragged to the start of the row`
`Reviewer(s): @chantbalci `
`Additional Info: simple fix, the "All" button is at the start of the row inside the reservation page`

Dragged the All button all the way to the start and is now auto focused

---

web/src/components/chatwidget/ChatWidget.js

`Name: @Electroviz `
`Related Issue: #443`
`Description:  Update now travel chatbot doesnt show when you are logged in as host`
`Reviewer(s): @chantbalci `

Update travel chatbot now doesnt show when loggedin as host

---

web/cypress/e2e/TestHouse.cy.js

test cypress
apartment,,house,vila
`Name: @Muubii `
- [x ] Delete my branch

Cypress test

---

web/cypress/e2e/TestHouse.cy.js

error now changed
Name: @Muubii 
- [ x] Bug fix

Update cypress test

---

web/cypress/e2e/TestHouse.cy.js

comment test alles

---

web/cypress/e2e/OnboardingprocessCamper.cy.js

this was probaly the error that cant get into aws

comment test camper TEST (chant)

---

web/cypress/e2e/OnboardingprocessBoat.cy.js

test again

---

web/public/index.html

Name: @RoozbehKouchaki 
Related Issue: #1110
Description: Updated GTM code with correct ID (GTM-NKNTZVVX)
Additional Info: None

Updated GTM code with correct ID (GTM-NKNTZVVX)

---

web/src/components/landingpage/OnboardingHost.js
web/src/components/landingpage/onboardingHost.css

Name: @Muubii 
Related Issue: #160 
css fix
- [x ] Bug fix
- [ x] No sensitive data (e.g., passwords, keys) are hardcoded

Fix style onboard

---

web/cypress/e2e/landingpage.cy.js
web/src/components/landingpage/OnboardingHost.js
web/src/components/landingpage/landing.module.css

Name: @Muubii 
Related Issue: #160  #1057 
Test landing page
small changes in placeholder to 0
- [x ] Bug fix
- [x ] Console.logs are deleted
- [ x] Comments are deleted
- [ x] Code has been tested in a local environment
- [ x] No sensitive data (e.g., passwords, keys) are hardcoded
Additional Info: merge acceptence into main when this is done

Test landing page

---

web/src/components/landingpage/OnboardingHost.js
web/src/components/landingpage/onboardingHost.css

o proceed, please check the following boxes:
I declare that this property is legitimate.
I agree to the general terms and conditions. with a ref to the page. You can only proceed if both checkboxes are selected.
Additionally, if you select both check-in and check-out options, you will be able to continue.
Name: @Muubii 
Related Issue: #786
To proceed, please check the following boxes:
I declare that this property is legitimate.
I agree to the general terms and conditions. with a ref to the terms and conditions.
You can only proceed if both checkboxes are selected.
Additionally, if you select both check-in and check-out options, you will be able to continue.
- [ x] No sensitive data (e.g., passwords, keys) are …

checkbox and confirm

---

web/package-lock.json
web/src/components/home/Accommodations.css
web/src/components/home/Accommodations.js

Changed accommodations view on homepage 3 > 4 per row.

---

web/src/components/booking/ListingDetails.js

Related Issue: #1129
Description: Hostprofile was not shown in de listingdetails and that is fixed now
- [ x] No sensitive data (e.g., passwords, keys) are hardcoded

Hostprofile in ListingDetails.js is visible again

---

web/cypress/e2e/landingpage.cy.js
web/src/components/landingpage/landing.module.css

Name: @Muubii 
Landing page fix without commets
- [ x] Bug fix

Cypress landing page fix

---

web/package-lock.json
web/package.json
web/src/components/hostchatbot/hostchatbot.css
web/src/components/hostchatbot/hostchatbot.js

Name: @[FejsalA]
Related Issue: #[493]
Description: [Changed it so the user will first be greeted with 3 options which will narrow done the decision tree. Making it so i can retrieve specific data and not all at once, increasing the efficency by alot.]

multi step form added, and major effiencency upgrade

---

web/cypress/e2e/TestHostDistribution.cy.js

Commented out test

---

web/src/components/home/Accommodations.css
web/src/components/home/Accommodations.js

Related Issue: #162 
Description: Added function to accommodations.js to dynamically get items per page depending on the device width. 

Added function for dynamic items per page on home. 

---

web/src/App.js
web/src/components/hostdashboard/HostRevenueCards/MonthlyComparison.css
web/src/components/hostdashboard/HostRevenueCards/MonthlyComparison.jsx
web/src/components/hostdashboard/HostRevenueCards/OccupancyRate.css
web/src/components/hostdashboard/HostRevenueCards/OccupancyRate.jsx
web/src/components/hostdashboard/HostRevenueCards/RevPAR.css
web/src/components/hostdashboard/HostRevenueCards/RevPAR.jsx
web/src/components/hostdashboard/HostRevenueCards/RevenueOverview.css
web/src/components/hostdashboard/HostRevenueCards/RevenueOverview.jsx
web/src/components/hostdashboard/HostRevenueStyle.css
web/src/components/hostdashboard/HostRevenues.js

Name: @RoozbehKouchaki 
Related Issue: #436 
Description: CSS Global Style Fixed
Additional Info: None

CSS Global Style Fixed

---

web/cypress/e2e/GuestDashboard.cy.js
web/src/components/base/Header.js
web/src/components/landingpage/OnboardingHost.js

Name: @Muubii 
Description: 10000 night to 150000
header now has a why domits
GuestDashboard cypress test is fixed

Faeture and testing done

---

web/cypress/e2e/OnboardingprocessBoat.cy.js
web/cypress/e2e/OnboardingprocessCamper.cy.js

Name: @Muubii 
Comment Boat Camper

Commenting Boat Camper code

---

web/cypress/e2e/TestHostDistribution.cy.js
web/src/components/hostdashboard/HostDistribution.js

Description: Fixed some error that made the test unable to run on acceptance branch

Host distribution

---

web/cypress/e2e/TestHostDistribution.cy.js

Description: Fixed a small error that checks the wrong url

Fixed a small error that checks the wrong url

---

web/cypress/e2e/TestHostDistribution.cy.js

Description: Test uitgecommend omdat die niet op acceptance branch wilt werken

Test uit gecommend

---

web/cypress/e2e/GuestDashboard.cy.js

Name: @Muubii 
Related Issue: #160 

Quickfix cypress test error

---

web/src/components/booking/DemoValidator.js
web/src/components/booking/ListingDetails.js

… the reserve button (that is disabled) "*This is a demo post and not bookable"
Name: @[GitHub mdinle]
Related Issue: #[1121]
Description: [Demo data is now not bookable and shows in the title (DEMO) and under the reserve button (that is disabled) "*This is a demo post and not bookable"]
Reviewer(s): @[GitHub chant]

Disable book btn for dummy data

---

web/src/components/home/Accommodations.js

Description: Added check to fomatData function if it's a camper or boat to ouput per day instead of per night to the price.

Tim styles - Accotype check homepage prices

---

web/src/components/base/Footer.js
web/src/components/careers/jobDetails.css
web/src/components/careers/jobDetails.js
web/src/components/home/Accommodations.css
web/src/components/home/Accommodations.js

Description: Added why domits button to home, job details page fix, fixed footer link text.

Tim styles - footer text fix / job details fix / added button to home

---

web/src/components/hostchatbot/hostchatbot.js

Host chat bot

---

web/cypress/e2e/TestHostDistribution.cy.js

Name: @Muubii 
Related Issue: #160 
Update test

update test distribution

---

web/cypress/e2e/TestHostDistribution.cy.js

sec try test

---

web/src/App.js
web/src/components/booking/BookingCalendar.module.css
web/src/components/booking/ListingDetails.js
web/src/components/hostdashboard/HostFinanceTab.css
web/src/components/hostdashboard/HostFinanceTab.js
web/src/components/hostdashboard/Pages.js

Host calender

---

web/package-lock.json
web/package.json
web/src/components/base/MenuBar.css
web/src/components/base/MenuBar.js
web/src/components/base/SearchBar.css
web/src/components/landingpage/Landing.js
web/src/components/landingpage/landing.module.css

Name: @Muubii 
Related Issue: #1116  #771
landing pag done
medium quickfix responsiveness and bottom menu look cleaner
- [ x] Big change (300+)
- [ x] Bug fix
- [ x] New feature
- [ x] NPM Packages installed
- [ x] Console.logs are deleted
- [ x] Comments are deleted

landing page/ medium fix

---

web/package-lock.json
web/package.json
web/src/components/booking/ListingDetails.js

Name: @Santoshskk 
Related Issue: #621 
Description: The renderIcons methode en de pop up method are now fixed so it reders the material UI and png icons
Reviewer(s): @Timmhart 

Floting booking engine

---

web/src/components/booking/ListingDetails.js

Related Issue: #621 
Description: Added all available icons from MUI to listing details. Some are still placeholders (checkmarks or icons closest to the one needed)

Tim fe - added icons to listingdetails

---

web/src/components/booking/ListingDetails.js

Prevent double booking by restricting reservations on already booked dates #1204

---

web/src/components/hostdashboard/HostFinanceTab.js

Description: button replaced with word link

made a link instead of a button

---

web/src/components/__tests__/ConfirmRegister.test.js

Related Issue: #1215 
Description: jest test had a wrong refrence import which is now deleted

jest test wrong refrence import

---

web/src/components/guestdashboard/GuestSettings.js
web/src/components/guestdashboard/Pages.js
web/src/components/guestdashboard/PagesDropdown.css
web/src/components/guestdashboard/guestdashboard.css
web/src/components/guestdashboard/paymentsguestdashboard.css
web/src/components/hostdashboard/HostReservations.module.css
web/src/components/hostdashboard/HostReviews.module.css
web/src/components/hostdashboard/Pages.js

Name: @Muubii 
Related Issue: #1212 
Responsiveness mobile guest done host expr missing chat and reservation
- [ x] Big change (300+)

Guest responsiveness

---

web/src/components/home/Accommodations.js
web/src/components/landingpage/OnboardingHost.js

Name: @Santoshskk 
Related Issue: #1149
Description: Changed the file type from jpg to webp
Additional Info: For the homepage it accepts jpg for the old images and webp for the new ones.

files are now compressed to .webp

---

web/src/components/base/Footer.js

Related Issue: nono its a uncomment

why domits is now seen in the footer again

---

package-lock.json
package.json
web/package-lock.json
web/package.json

Name: @RobinvnD 
Related Issue: [Dependabot alerts](https://github.com/domits1/Domits/security/dependabot) [#61](https://github.com/domits1/Domits/security/dependabot/61)

Fix-Path-Regexp

---

web/src/components/hostdashboard/HostFinanceTab.css
web/src/components/hostdashboard/HostFinanceTab.js
web/src/components/hostdashboard/HostPropertyCare.css
web/src/components/hostdashboard/HostPropertyCare.js

Related Issue: none
Description: quick inline css removed

inline code removed

---

web/src/components/about/Whydomitstwo.js
web/src/components/about/whydomits.css

Name: @Muubii 
Related Issue: #685 
Description: Why Domits V2 Most of the things are like in figma i added a back to top button to go back to the menu bar and i wil work tommorow on the little part finish it up.
- [ x] New feature
- [ x] No sensitive data (e.g., passwords, keys) are hardcoded
Additional Info: Tomorow touching things up

Why domits page v2 basics

---

web/src/components/hostdashboard/CalendarComponent.js
web/src/components/hostdashboard/HostDistribution.js
web/src/components/landingpage/OnboardingHost.js
web/src/components/landingpage/onboardingHost.css

Related Issue: #1226 
Description: I added a condition for the DateRanges of a accommodation. The Host can now set a minimum of days for a Date Range object.

Channel Management Requirements #1226

---

web/src/components/hostdashboard/CalendarComponent.js

Related Issue: #1255 
Description: Small modification to a if statement. Also when changing the DateRanges, first (if needed) change the minimal stay (arrival) before selecting a new DateRange. Otherwise it would not update the minimum properly.

Bug fix channel management requirements #1226

---

web/src/components/chat/ChatPage.module.css
web/src/components/chat/ContactItem.js
web/src/components/chat/ContactItem_Guest.js

Name: @2174951 
Related Issue: #536
Description: fixed contact loading with the wrong name

Improved contact and request loading

---

web/src/components/hostdashboard/CalendarComponent.js
web/src/components/landingpage/OnboardingHost.js
web/src/components/landingpage/onboardingHost.css

Related Issue: #1258  
Description: Fixed the bug where the DateRanges and minimum and maximum stays did not work properly. Also renamed few variables: minimumStayArrival -> minimumStay, maximumStayArrival -> maximumStay, minimumStayThrough -> minimumBookingPeriod

Fix for Onboarding DateRanges Calender #1258

---

web/src/components/guestdashboard/guestdashboard.css
web/src/components/hostdashboard/HostDashboard.module.css
web/src/components/hostdashboard/HostHomepage.css
web/src/components/hostdashboard/HostReservations.module.css
web/src/components/hostdashboard/HostSettings.js
web/src/components/hostdashboard/settingshostdashboard.css
web/src/components/utils/PageSwitcher.module.css

Description: Styling changes host and guest dashboards
Reviewer(s): @chantbalci @mdinle 

Styling changes host and guest dashboards.

---

web/src/components/base/Header.js
web/src/components/guestdashboard/guestdashboard.css

Related Issue: #1260 
Description: Changed copyright to switch between host and guest.

Header quick fix #1260 and guest dashboard navigation quick fix

---

app/Domits/package-lock.json
app/Domits/src/screens/bookingprocess/bookedAccommodation.js
app/Domits/src/screens/bookingprocess/bookingProcess.js
app/Domits/src/screens/bookingprocess/paymentAccepted.js
app/Domits/src/screens/bookingprocess/paymentDeclined.js
app/Domits/src/screens/bookingprocess/simulateStripe.js
app/Domits/src/screens/detailpage.js

Related Issue: #250 
Description: First version of dynamically showing data from the database into to app version of the booking engine. Have not worked on the styling yet.

App guest experience home tab booking engine #250

---

web/src/components/guestdashboard/guestdashboard.css

Bug fix missing a bracket in css

---

web/src/components/booking/BookingOverview.js
web/src/components/booking/bookingoverview.css

Related Issue: # -
Description: Styling changes booking engine.

Booking overview fe changes

---

app/Domits/package-lock.json
app/Domits/package.json
web/src/components/landingpage/OnboardingHost.js
web/src/components/landingpage/onboardingHost.css

Name: @Muubii 
Related Issue: #1057 
Description: Changed the from til from default input time to option time 
- [x ] Optimalization

Optimasation / feature select time house rules

---

web/src/components/about/Whydomitstwo.js
web/src/components/about/whydomits.css

Name: @Muubii 
Related Issue: #685 
Description: changes into why domits

Why domits changes better styling

---

web/cypress/e2e/guestDashboardSettings.cy.js

Name: @Muubii 
Related Issue: #595 
Description: cy test guest settings
- [x ] Bug fix

Test guest settings

---

app/Domits/src/components/utils/ImageSlider.js
app/Domits/src/screens/hostdashboard/dashboard.js

Name: @Muubii 
Related Issue: #1291 
Description:Fixes stylinig from host dashboard app

Styling fixed

---

web/src/components/base/Header.js
web/src/components/base/base.css

Trustpilot added to header

---

package-lock.json
package.json
web/src/components/landingpage/Landing.js
web/src/components/landingpage/landing.module.css

Name: @Muubii 
Related Issue: #771 
Description: Changes yeasterday landing page mobile revieuws respon and some optimalisation
- [x ] Big change (300+)
- [x ] New feature
- [x ] NPM Packages installed

Landing page quickfix/responsiveness

---

web/src/components/careers/jobs.json

Description: Fixed job data "business developer"

Fixed job data "business developer"

---

app/Domits/package-lock.json
app/Domits/package.json
web/src/components/hostdashboard/HostRevenueCards/ADRCard.css
web/src/components/hostdashboard/HostRevenueCards/ADRCard.jsx
web/src/components/hostdashboard/HostRevenueCards/OccupancyRate.css
web/src/components/hostdashboard/HostRevenueCards/OccupancyRate.jsx
web/src/components/hostdashboard/HostRevenues.js
web/src/components/hostdashboard/Loading.css
web/src/components/hostdashboard/Loading.js

Name: @RoozbehKouchaki 
Related Issue: #436 
Description: ADR and Occupancy Rate card
Additional Info: NONE

New Features ( Ocuppancy rate and ADR )

---

web/src/components/home/Accommodations.css

Background color fixed

---

web/src/components/__tests__/Accommodation.test.js

Name: @Muubii 
Description: [Test comment cuz deploy not work](https://github.com/domits1/Domits/commit/7a22586e50024f7bc4b941d0eeef6506aafc6820)

Test comment cuz deploy not work

---

web/src/components/base/Footer.js
web/src/components/ninedots/ninedots.css
web/src/components/ninedots/travelinnovation.js

Design travel and small style
Name: @Muubii 
Related Issue: #
Description: optimalisation travelinnovation

Fix travelinnovation

---

web/src/components/contact/Contact.js
web/src/components/hostdashboard/HostRevenueCards/OccupancyRate.css
web/src/components/hostdashboard/HostRevenueCards/OccupancyRate.jsx
web/src/components/hostdashboard/HostRevenues.js

Name: @RoozbehKouchaki 
Description: Fixed the message function in the contact page
Additional Info: No

Fixing Contact

---

web/public/index.html
web/public/manifest.json
web/src/components/contact/Contact.js
web/src/components/home/Accommodations.css
web/src/components/home/Accommodations.js

Name: @Muubii 
Description: Quickfix button doesnt go down contact when put file inside
The home page acco can click now <> also the name of the acco is also back
favicon change pls merge in main soon to check if the change worked

Quickfix button doesnt go down contact

---

app/Domits/src/components/Acommodations.js
app/Domits/src/screens/hostdashboard/CalendarComponent.js
app/Domits/src/screens/hostdashboard/HostCalendar.js
app/Domits/src/screens/hostdashboard/dashboard.js
app/Domits/src/screens/hostdashboard/listings.js
web/src/components/booking/BookingOverview.js
web/src/components/booking/ListingDetails.js
web/src/components/chat/Chat.js
web/src/components/chatwidget/ChatWidget.js
web/src/components/home/Accommodations.js
web/src/components/hostchatbot/hooks/useFetchData.js
web/src/components/hostdashboard/Calendar.js
web/src/components/hostdashboard/CalendarComponent.js
web/src/components/hostdashboard/HostCalendar.js
web/src/components/hostdashboard/HostDashboard.js
web/src/components/hostdashboard/HostDistribution.js
web/src/components/hostdashboard/HostListings.js
web/src/components/hostdashboard/Hostchat.js
web/src/components/landingpage/OnboardingHost.js
web/src/components/listingdetails/ListingDetails.js

Description: Change api because i accidentaly deleted the  whole api part of acco in aws im sorry

Change api because i accidentaly deleted the  whole api part of acco

---

app/Domits/src/screens/detailpage.js
app/Domits/src/screens/hostdashboard/HostCalendar.js
app/Domits/src/screens/hostdashboard/dashboard.js
app/Domits/src/screens/hostdashboard/listings.js
web/src/components/booking/BookingOverview.js
web/src/components/booking/ListingDetails.js
web/src/components/chat/Chat.js
web/src/components/chatwidget/ChatWidget.js
web/src/components/hostchatbot/hooks/useFetchData.js
web/src/components/hostdashboard/Calendar.js
web/src/components/hostdashboard/CalendarComponent.js
web/src/components/hostdashboard/HostCalendar.js
web/src/components/hostdashboard/HostDashboard.js
web/src/components/hostdashboard/HostListings.js
web/src/components/hostdashboard/Hostchat.js
web/src/components/landingpage/OnboardingHost.js
web/src/components/listingdetails/ListingDetails.js

Related Issue: #1422
Description: het is in een Resources waar je overzichtelijk kan zien in api maar de listing details werkt niet

second update

---

app/Domits/src/screens/hostdashboard/listings.js
web/src/components/home/homePage.js
web/src/components/hostdashboard/HostListings.js

Listing v3 last one

---

web/src/components/guestdashboard/GuestDashboard.js
web/src/components/guestdashboard/GuestSettings.js
web/src/components/hostdashboard/HostSettings.js

Related Issue: #1411
Description: user email and name are now updated (lambda naming)

user updates

---

.idea/misc.xml
app/Domits/android/app/build.gradle
app/Domits/ios/Domits.xcodeproj/project.pbxproj
app/Domits/ios/Podfile.lock
app/Domits/package-lock.json
app/Domits/package.json
web/src/components/booking/BookingOverview.js
web/src/components/hostdashboard/HostDashboard.js
web/src/components/hostdashboard/HostFinanceTab.js
web/src/components/hostdashboard/HostListings.js
web/src/components/hostdashboard/HostRevenues.js
web/src/components/hostdashboard/Pages.js
web/src/components/landingpage/OnboardingHost.js

Related Issue: #1411
Description: lambda links changed

lambda updates

---

web/src/components/hostdashboard/HostFinanceTab.js

comments and logs removed

---

web/src/components/booking/BookingOverview.js
web/src/components/hostdashboard/HostDashboard.js
web/src/components/hostdashboard/HostListings.js
web/src/components/hostdashboard/HostRevenues.js
web/src/components/landingpage/OnboardingHost.js

Related Issue: #1435
Description: one some pages the stripe checking didnt work properly in which it caused confusion of functioning
Reviewer(s): @Chanlyj 

checkifstripe parsing error fixed

---

app/Domits/src/header/header.js
app/Domits/src/screens/guestdashboard/guestDashboard.js
app/Domits/src/screens/homeScreen.js
app/Domits/src/screens/hostdashboard/hostDashboard.js

Related Issue: #1438
Description: deletion of the redunant pages

checklist app error/bug/warnings

---

web/src/components/home/components/HomeSearchBar.css

Description: fix searchbar responsive

responsiveness searchbar

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/home/components/HomeSearchBar.css
web/src/components/home/components/SearchBar.jsx
web/src/components/home/components/base.css
web/src/components/home/homePage.css
web/src/components/home/homePage.js

Name: @Muubii 
Description:responsiveness homepagex

FIx searchbar responsiveness

---

app/Domits/src/header/header.js
web/src/components/home/Header.js
web/src/components/home/components/HomeSearchBar.css
web/src/components/home/components/bases.css

Related Issue: #
Description:last fix header and searchbar also fixed <> in the acco cards

FIx header and <>

---

web/src/components/booking/ListingDetails.js
web/src/components/booking/listing.css
web/src/components/home/components/HomeSearchBar.css
web/src/components/home/components/SearchBar.jsx
web/src/components/home/homePage.js

Name: @Muubii 
Related Issue: #1340
Description:fix homepage width 725px searchbar
and some other responsiveness
listing details chronicly orderd
house rules implemented
and fix day/night for boat and house

Fix homepage and listingdetails function added

---

web/cypress/e2e/homePage.cy.js
web/src/components/base/SearchBar.jsx
web/src/components/home/Header.js
web/src/components/home/components/bases.css
web/src/components/home/homePage.css
web/src/components/home/homePage.js

Fix header and searchbar and test

---

web/src/components/hostdashboard/HostPricing.js

Related Issue: #1226 
Description: Made it so when rent and/or cleaning fee are lower than 0 (negative numbers) give a error message

Save bugs #1226

---

web/cypress/e2e/homePage.cy.js
web/public/index.html
web/public/manifest.json

Name: @Muubii 
Related Issue: #
Description:cypress test failed here is now fix and fix on favicon domits
Big change (300+)

Fix cypress error homepage and Favicon Domits

---

web/src/components/about/ReleaseUpdates.js
web/src/components/base/Header.js
web/src/components/home/Header.js

Name: @Muubii 
Related Issue: #1340 

drowpdown fix and new post x

---

web/cypress/e2e/homePage.cy.js
web/src/App.js
web/src/components/guestdashboard/Pages.js
web/src/components/hostdashboard/HostFinanceTab.js
web/src/components/hostdashboard/Pages.js

Name: @Muubii 
Related Issue: #
Description: 
Homepage test add time wait
app js propety-care to housekeeping
finance tab change text
pages update path

Homepage test, app route finance tab

---

web/src/App.js
web/src/pages/helpdesk/Helpdesk.js
web/src/pages/helpdesk/helpdesk.css
web/src/pages/landingpage/Faq.js

error fix from helpdesk

---

web/src/components/__tests__/pageNotFound.test.js

fix error in the pipline path

---

.github/workflows/ci.yml

Name: @Muubii 
Related Issue: #1088 
Description: wrong path

wrong one this one fix

---

.github/workflows/ci.yml
web/package-lock.json

package and ci path

---

web/src/tests/pageNotFound.test.js

Name: @Muubii 
Related Issue: #371 
Description: path fix jest test
- [ x] Bug fix

Jest test fix path

---

web/src/tests/cypress/e2e/homePage.cy.js

test comment

---

web/src/features/hostdashboard/HostPricing.js

Configure Dynamic Pricing Uncommended

---

web/src/App.js
web/src/components/base/base.css
web/src/features/hostdashboard/HostDashboard.js
web/src/features/hostdashboard/HostFinanceTab.js
web/src/features/hostdashboard/HostListings.js
web/src/features/hostdashboard/HostPricing.js
web/src/features/hostdashboard/Hostchat.js
web/src/features/hostdashboard/Pages.js
web/src/features/hostdashboard/hostdistribution/pages/HostDistribution.js
web/src/features/hostdashboard/hostdistribution/styles/HostDistribution.css
web/src/features/hostonboarding/components/ImagePreview.js
web/src/features/hostonboarding/hooks/usePhotos.js
web/src/features/hostonboarding/views/PropertyPhotosView.js
web/src/hooks/useSelfLearningPricingModel.js

Bekir branch

---

app/Domits/.env.example
app/Domits/babel.config.js
app/Domits/package.json
app/Domits/src/navigation/appNavigation.js
app/Domits/src/screens/detailpage.js
web/.env.example
web/package.json
web/src/dotenv.js

Name: @Sandervg03
Related Issue: #1577
Description: Adds .env functionality to both web and app. Read the .env.example files for information on how to use .env.

App/Web | Add .env functionality

---

app/Domits/App.js
app/Domits/src/header/header.js
app/Domits/src/navigation/accountNavigationStack.js
app/Domits/src/navigation/appNavigation.js
app/Domits/src/navigation/mainNavigationStack.js
app/Domits/src/navigation/messagesStackNavigator.js
app/Domits/src/screens/account.js
app/Domits/src/screens/detailpage.js
app/Domits/src/screens/homeScreen.js
app/Domits/src/screens/login/confirmMail.js
app/Domits/src/screens/login/loginScreen.js

Related Issue: #45 
Description: I refactored the navigation stacks so they are properly ordered (for as far as I've gotten thus far). I also did some UX cleanup and refactoring (mostly editing navigation and hooks + removing components we don't plan on using)

App | Preparation google play store release | UX Cleanup + Navigation Refactor

---

app/Domits/android/app/build.gradle
app/Domits/android/gradle.properties
app/Domits/src/features/auth/DeleteAccount.js
app/Domits/src/header/header.js
app/Domits/src/screens/account.js
app/Domits/src/screens/homeScreen.js

Related Issue: #45 
Description: Dynamically renders bookings button in header. Also seperates DeleteAccount functionality to a standalone function for reusability. Finally removes hardcoded 'Android Application Bundle' (AAB) properties and passcodes.
Reviewer(s): @Stephanie-Lahmann @Muubii 
Additional Info: N/A

App | Android App Release #45 | UX Cleanup + seperating delete account function for reusability.

---

web/src/tests/cypress/e2e/Guest/GuestDashboard.cy.js
web/src/tests/cypress/e2e/Host/Hostdashboard.cy.js
web/src/tests/cypress/support/commands.js

Name: @Mary-any 
Related Issue: #88 
Description:  Security: Replaced real email and password with dummy credentials to protect sensitive data.
Testing: Completed all TODOs in Cypress tests to improve test coverage and maintainability.
Reviewer(s): @Muubii 

Cypress testing

---

web/src/components/base/FilterButton.css
web/src/components/base/FilterButton.jsx
web/src/components/base/FilterModal.css
web/src/components/base/FilterModal.js
web/src/components/base/Header.js
web/src/pages/home/Accommodations.css
web/src/pages/home/FiltersMain.jsx

Description: de css geoptimaliseerd todat de accocards op twee paginas hetzelfde er uit te komen zien

Price filter

---

web/src/pages/home/Accommodations.css
web/src/pages/home/homePage.css

fixing the width issues on two homepages for accommodations

---

web/src/components/base/SkeletonLoader.css
web/src/pages/home/Accommodations.js
web/src/pages/home/FilterLogic.jsx
web/src/pages/home/FilterMain.css
web/src/pages/home/FilterUi.jsx
web/src/pages/home/homePage.css
web/src/pages/home/homePage.js

Related Issue: # https://github.com/domits1/Domits/issues/18
Description: So i made an new branch with my old changes and thats because on my old branch i missend some important files that were removed at some point... those "new" changes that are now being made were already created last week but in short, i splitted up the ui from logic on filters to make it more readable, i also added api that now makes connection to lambda function and and process the input from user to show the right accommodation based on price for now.
- [-] Comments are deleted (I added some comments to make it more understandable for other interns...)
Reviewer(s): …

Made new branch to fix the missing package-lock files + made changes to how skeletonloader works

---

web/src/components/base/Footer.js
web/src/components/base/SearchBar.jsx
web/src/components/base/SkeletonLoader.css
web/src/components/base/base.css
web/src/features/chatwidget/ChatWidget.js
web/src/pages/contact/Contact.js
web/src/pages/home/Accommodations.css
web/src/pages/home/Accommodations.js
web/src/pages/home/homePage.css
web/src/pages/home/homePage.js

Related Issue: #https://github.com/domits1/Domits/issues/1633
Description: ik heb de gevraagde changes toegepast die binnen een issue zatten.
- [] No sensitive data (e.g., passwords, keys) are hardcoded
Reviewer(s): @SHvanderWilt 

Quick fixes and kleine details verbeteren aan de homepage

---

web/package-lock.json
web/package.json
web/src/components/base/SearchBar.jsx
web/src/pages/home/FilterMain.css
web/src/pages/home/FilterUi.jsx

Description: I made some nice audition to searchbar and filter logic, for filters i removed a button to apply changes and after applying the price filter the changes will be automatically executed without pressing on a submit button. For searchbar i fixed a bug where if you wanted to search accommodation from other page then /home that the results wouldn't show up, now it's the case :D

Made some necessery optimalisations to the search and filter logic

---

web/src/features/guestdashboard/guestdashboard.css
web/src/pages/about/about.css
web/src/pages/contact/contact.css
web/src/pages/home/homePage.css
web/src/pages/landingpage/landing.module.css
web/src/pages/whydomits/whydomits.css

Name: @2174951 
Description: link returned to original link styling, because of removed global styling. Fixed now

a (links) styling fixed

---

.github/workflows/ci.yml
sonar-project.properties
web/src/tests/cypress/e2e/Guest/GuestBookingEngine.cy.js

Name: @Ryan
Force push ... 
Reviewer(s): @Mary-any

Acceptance two point oh

---

web/src/components/base/Footer.js
web/src/features/auth/Register.css
web/src/pages/home/Accommodations.css
web/src/pages/home/FilterLogic.jsx

Description:  Small quickfixes from my old pr that was corrupted by demons.

quickfixes changes from my old pr (Those all not all the changes )

---

web/src/App.js

Chat widget uit de html code gehaald omdat het momenteel nog niet af is.
Name: Marijn Klappe
Related Issue: Geen issue
resolves Geen issue
Description: Chat widget removed
- ja
- [ x] Bug fix

Chat widget

---

web/src/features/hostonboarding/views/PropertyCalendarAvailabilityView.js

Staying night optie van de hostonboarding weg gehaald.
Name: Marijn Klappe
Related Issue: heeft geen issue
resolves heeft geen issue
Description: staying night optie van de hostonboarding weg gehaald

staying_nights

---

web/src/App.js
web/src/components/base/Header.js
web/src/features/guestdashboard/Pages.js
web/src/features/hostdashboard/Pages.js

Name: Marijn Klappe
Related Issue: geen issue
Description: review visuals removed

Host onboarding calender

---

web/src/pages/home/AccommodationCard.js
web/src/pages/home/homePage.js
web/src/pages/home/services/fetchProperties.js

Related Issue: #1629 
resolves #1629 
Description: Implements new backend api for fetching boat-, camper- and trending properties.
Reviewer(s): @SHvanderWilt 
Additional Info:

Web homepage fetch

---

web/src/pages/home/Accommodations.js
web/src/pages/home/homePage.js
web/src/pages/home/services/fetchProperties.js

Related Issue: #1629
Description: Adds correct progress indicator.
Reviewer(s): @SHvanderWilt 

Updates progress indicator

---

web/eslint.config.mjs

Quickfix eslint

---

web/src/tests/cypress/e2e/Pages/TestMessagingFeature.cy.js
web/src/tests/cypress/support/commands.js

Name: Jasper Aurelio Villas
Related Issue: geen issue
resolves geen issue
Description: This is a cypress testing for the messaging feature.

added cypress testing for the messaging feature

---

web/src/components/base/FilterButton.jsx
web/src/components/base/Footer.js
web/src/components/base/Header.js
web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx
web/src/components/base/base.css
web/src/features/auth/Register.css
web/src/pages/home/Accommodations.css
web/src/pages/home/Accommodations.js
web/src/pages/home/components/bases.css
web/src/pages/landingpage/landing.module.css

… styles, and update Accommodations.css max-width

Enhance UI components

---

web/src/tests/cypress/e2e/Pages/TestHowItWorksPage.cy.js

Name: Jasper Aurelio Villas
Related Issue: geen issue
resolves geen issue
Description: added basic cypress testing for the How it works page. simple navigation and element check

added cypress testing for How it works page

---

web/src/pages/productupdates/ReleaseUpdates.js

Name: Jasper Aurelio Villas
Related Issue: Geen issue
resolves Issue
Description: Manually added february product update

added february update

---

web/src/features/hostdashboard/HostFinanceTab.js

Name: @MC38-03 
Related Issue: #1664 #1665 

Decimals reduce to 2 on payment amount.

---

web/src/features/verification/hostverification/hooks/useStripeVerification.js

Name: @Ryan-Reddy 
resolves #1784
Description: Comments out missing env file, stripe should be used in backend for production, not front end.

temp fix for the stripe error

---

web/src/features/hostdashboard/hostcalendar/styles/Calender.scss
web/src/features/hostdashboard/hostcalendar/utils/addToDate.js
web/src/features/hostdashboard/hostcalendar/utils/convertDateToHTML.js
web/src/features/hostdashboard/hostcalendar/utils/convertToDBDates.js
web/src/features/hostdashboard/hostcalendar/utils/convertToDate.js
web/src/features/hostdashboard/hostcalendar/utils/decodeDateNumber.js
web/src/features/hostdashboard/hostcalendar/utils/deleteDate.js
web/src/features/hostdashboard/hostcalendar/utils/getCalDays.js
web/src/features/hostdashboard/hostcalendar/utils/getMonthName.js
web/src/features/hostdashboard/hostcalendar/utils/newDate.js
web/src/features/hostdashboard/hostcalendar/utils/sortDates.js
web/src/features/hostdashboard/hostcalendar/views/Calender.js
web/src/features/hostonboarding/views/PropertyCalendarAvailabilityView.js

Name: @deloads 
Reviewer(s): @SHvanderWilt @kacperfl 

Calender styling fix marijn

---

web/src/components/base/SearchBar.css
web/src/components/base/SearchBar.jsx

Description: Ik heb in dit pr alle of bijna alle inline styling uit de search-bar gehaald en in aparte css bestand gezet, de stylingen waren voornamelijk css voor de packages maar nu is de SearchBar.jsx veel meer leesbarder, ik wil de css nog naar SCSS veranderden dus dat komt nog maar de css zelf is heel groot  dus dat duurt wel even.
Daarnaast lijken er alof er heel wat changes zijn maar het komt door inspringen van prettier, daarnaast een kritiek classname BUTTON aangepast waardoor het elke button op de website heeft aangepast (thx Damien) die heb ik verwijderd omdat die nie gebruikt werd
- [] Pull request title is descriptive and includes the issue number
All boxes must be checked in …

alle inline styling in de searchbar uitgehaald en in aparte css gezet (wordt scss)

---

web/src/features/guestdashboard/Pages.js

Guest dashboard flickering

---

web/src/features/bookingengine/listingdetails/pages/listingDetails2.js
web/src/styles/sass/booking-engine/listingDetails.scss

Description: Adds quickfix for missing error handling.

Adds quickfix error handling for listing details.

---

web/src/features/bookingengine/listingdetails/services/fetchPropertyById.js
web/src/pages/home/services/fetchProperties.js

Description: Edits fetch requests for GET method on home-, landing- and listing-details-page

Edits fetch requests to implement new formats

---

web/src/pages/home/Accommodations.js
web/src/pages/home/homePage.js
web/src/pages/home/services/fetchProperties.js

Description: Adds handling for lastEvaluatedKey to make pagination easier.
_- all files are just edited with: alt + shift + f. To format the code, it just removes a bunch of lines but the only thing I actually changed is the fetch method and how that is handled. …

Adds lastEvaluatedKey attribute from backend to know if there will be a next page.

---

web/src/features/bookingengine/BookingSend.js

Related Issue: n/a
Closes: n/a
Description: Lambda function makes use of authorization. Bookings submitted won't be able to be registered due to this needed authorization token. This PR contains a few lines of codes to fix this.
Changed:
**Lambda:**General-Bookings-CRUD-Bookings-develop
src\features\bookingengine\BookingSend.js - made use of an get auth token hook.
_4. Open a “Pull Request” …

Booking Create with Authorization

---

web/src/features/hostdashboard/hostcalendar/utils/convertToDBDates.js
web/src/features/hostdashboard/hostcalendar/views/Calender.js
web/src/features/hostonboarding/views/11_PropertyAvailabilityView.js

calender dates worden nu opgeslagen
Name: @deloads 
Related Issue: geen issue
Closes #[issue number] (only if it should close it)
As the Pull Requester, **you …

Calender Dates fix

---

app/Domits/src/screens/home/screens/Home.js
app/Domits/src/screens/home/views/PropertyCard.js
app/Domits/src/services/wishlist/AddToWishlist.js
app/Domits/src/services/wishlist/GetWishlist.js
app/Domits/src/services/wishlist/RemoveFromWishlist.js

Related Issue: #341 
Description: Implements @Mary-any 's wishlist feature to homepage in app, also removes hostId from title in PropertyCard.
As the Pull Requester, **you are responsible for your own pull …

Adds Wishlist feature, removes hostId from PropertyCard title

---

web/src/features/hostdashboard/hostcalendar/utils/convertToDBDates.js

Name: @deloads 
Related Issue: 
Closes 
1. Send a message (with PR link) to the …

Calender-timezone-date-fix

---

web/src/features/bookingengine/BookingSend.js
web/src/features/bookingengine/services/BookingFetchData.js

Removes the need to need to use another const, because the await response.json already returns what is needed, and the body is not nested in a object anymore.
Related Issue: #[issue number]  none
Closes #[issue number] (only if it should close it) none
Description: Small fix, changes a few lines and does no harm all together. Did show another major part which needs to be fixed, which will be addressed asap.
_3. Test …

Fix the booking create again

---

app/Domits/src/features/bookingengine/components/BookingEngineGuestsPopup.js
app/Domits/src/features/bookingengine/screens/BookingEngineScreen.js
app/Domits/src/features/bookingengine/styles/BookingEngineStyles.js
app/Domits/src/features/bookingengine/utils/CalculateNumberOfNights.js
app/Domits/src/screens/propertyDetailsScreen/screens/propertyDetailsScreen.js
app/Domits/src/screens/propertyDetailsScreen/views/SelectBookingDatesCalendarView.js
app/Domits/src/services/availability/bookingRepository.js

Related Issue: App booking overview.
Description: Implements Booking API to fetch previous reservations. Also implements new calendar in the booking overview. Finally adds a clickEnabled value so we can reuse this component in all calendar related components.
I am going to be refactoring and cleaning up the code of the bookingoverview after this merge so I can just simply create a branch from acceptance so my branche is fully up to date. Tests will be added after the clean up.
_1. …

App implement booking overview

---

web/src/App.js
web/src/features/auth/Register.js
web/src/features/auth/confirmEmail/ConfirmEmailView.js
web/src/features/hostaiagent/hooks/useUserDetails.js
web/src/styles/sass/app.scss

Related Issue: #1661 
Closes #[issue number] (only if it should close it)
As the Pull Requester, **you are responsible for your own …

Ragister issue 1661 marijn

---

web/src/components/base/SearchBar.jsx
web/src/pages/home/Accommodations.js

Closes #[issue number] (only if it should close it)
Description: Just updated the endpoint of the api url, th searching is technically working but it isnt yet optimal for instance the loading is pretty long, the skeletonloader doesnt update in right time. But for now its sufficient
_5. Discuss and request review …

Updated the api url endpoint 

---

app/Domits/src/features/bookingengine/global/views/PricingView.test.js
app/Domits/src/features/bookingengine/paymentcancelled/screens/PaymentCancelled.js
app/Domits/src/features/bookingengine/paymentcancelled/tests/CancelledView.test.js
app/Domits/src/features/bookingengine/paymentcancelled/tests/PaymentCancelledScreen.test.js
app/Domits/src/features/bookingengine/paymentconfirmed/screens/PaymentConfirmed.js
app/Domits/src/features/bookingengine/paymentconfirmed/tests/ConfirmedView.test.js
app/Domits/src/features/bookingengine/stripe/screens/StripePayment.js
app/Domits/src/features/bookingengine/stripe/tests/StripePayment.test.js
app/Domits/src/features/calendar/CalenderComponent.test.js
app/Domits/src/screens/propertyDetailsScreen/tests/propertyDetails.test.js
app/Domits/src/services/availability/bookingRepository.js
app/Domits/src/services/availability/test/testBookingRepository.js

Closes #816 
Description: Implements booking create and confirmation.
_- testing files.
1. Send a message (with PR link) to the reviewer you choose.  
2. If they don’t respond within a …

Implements booking create and confirmation.

---

app/Domits/src/features/bookingengine/paymentconfirmed/screens/PaymentConfirmed.js
app/Domits/src/screens/guestdashboard/screens/GuestBookings.js
app/Domits/src/screens/guestdashboard/styles/BookingView.js
app/Domits/src/screens/guestdashboard/views/BookingView.js
app/Domits/src/services/availability/bookingRepository.js
app/Domits/src/services/property/propertyRepository.js

Related Issue: #816 
Description: Adds booking overview.
1. Send a message (with PR link) to the reviewer you choose.  
2. If they …

App implement guest booking overview

---

frontend/web/src/features/guestdashboard/GuestWishlist.js
frontend/web/src/features/guestdashboard/components/GuestActions.js

Name: @Mary-any 
Description: [Added code from last night to new structure
As the Pull …

Added code from last night to new structure

---

frontend/web/src/features/guestdashboard/components/GuestActions.js
frontend/web/src/features/guestdashboard/components/WishlistChoice.js
frontend/web/src/features/guestdashboard/services/wishlistService.js
frontend/web/src/pages/home/AccommodationCard.js
frontend/web/src/pages/home/Accommodations.css

Name: @Mary-any 
- Related Issue: #1980 
Description: ✨ feat: add WishlistChoice component with PATCH support to move accommodation
As the Pull Requester, **you are …

Guest wishlist v3

---

backend/functions/PropertyHandler/controller/propertyController.js

Replace "assert" to "with" for type assertion for responseHeaders. (Quickfix)

---

backend/CD/template/events/get.js
backend/CD/template/function/business/model/user.js
backend/CD/template/function/business/service/service.js
backend/CD/template/function/controller/controller.js
backend/CD/template/function/data/database/connect.js
backend/CD/template/function/data/repository.js
backend/CD/template/function/data/systemManagerRepository.js
backend/CD/template/function/util/constant/responseHeader.json
backend/CD/template/function/util/mapping/userMapping.js
backend/ORM/schema.psql
backend/package-lock.json
backend/package.json

Description: Implements Aurora DSQL in template  function, also adds postgresql schema for Aurora DSQL database.
1. Send a message …

Implement Aurora DSQL in template function.

---

backend/ORM/models/Booking.js
backend/ORM/models/Property_Pricing.js
backend/ORM/schema.psql
backend/functions/PropertyHandler/business/model/propertyPricing.js
backend/functions/PropertyHandler/business/service/propertyBuilder.js
backend/functions/PropertyHandler/data/repository/propertyPricingRepository.js
backend/functions/PropertyHandler/util/mapping/pricing.js
frontend/app/Domits/src/features/bookingengine/global/views/PricingView.js
frontend/app/Domits/src/features/translation/store/en.json
frontend/app/Domits/src/features/translation/store/nl.json
frontend/app/Domits/src/screens/propertyDetailsScreen/views/pricingView.js
frontend/web/src/features/bookingengine/BookingOverview.js
frontend/web/src/features/bookingengine/listingdetails/components/pricing.js

- Related Issue: #138 
Description: Adds some variables to orm and implements them in front- and backend.
1. Send a message (with …

Add variables to orm

---

backend/functions/PropertyHandler/business/model/propertyPricing.js
backend/functions/PropertyHandler/util/mapping/pricing.js

Add variables to db

---

frontend/web/src/App.js
frontend/web/src/components/messages/Messages.js
frontend/web/src/features/hostdashboard/HostCalendar.js
frontend/web/src/features/hostdashboard/HostDashboard.js
frontend/web/src/features/hostdashboard/HostFinanceTab.js
frontend/web/src/features/hostdashboard/HostListings.js
frontend/web/src/features/hostdashboard/HostPayments.js
frontend/web/src/features/hostdashboard/HostReservations.js
frontend/web/src/features/hostdashboard/HostSettings.js
frontend/web/src/features/hostdashboard/Housekeeping.js
frontend/web/src/features/hostdashboard/Pages2.js
frontend/web/src/features/hostdashboard/hostpricing/views/HostPricing.js
frontend/web/src/features/hostdashboard/mainDashboardHost.js
frontend/web/src/styles/sass/features/guestdashboard/Pages.scss

alle oude changes overgezet van vorige branch
Name: @deloads 
_All …

changes overzetten

---

frontend/app/Domits/src/features/hostonboarding/styles/HostOnboardingStyles.js
frontend/app/Domits/src/features/hostonboarding/utils/propertyFormData.js
frontend/app/Domits/src/features/hostonboarding/views/OnboardingName.js
frontend/app/Domits/src/features/translation/store/nl.json

- Related issue: #1367
Description: Implemented app onboarding page for setting property name/title.
_No refactors_
_No changes to npm_
1. Send a message (with PR link) to the …

1367 app onboarding name

---

backend/functions/PropertyHandler/business/model/propertyPricing.js
backend/functions/PropertyHandler/data/repository/propertyAmenityRepository.js
backend/functions/PropertyHandler/data/repository/propertyAvailabilityRepository.js
backend/functions/PropertyHandler/data/repository/propertyRuleRepository.js
backend/package-lock.json
backend/package.json
backend/test/PropertyHandler/builder-property-based.test.js
backend/test/PropertyHandler/index.test.js
backend/test/PropertyHandler/routing-unit.test.js

Description: Adds some property-based and routing tests, also quickfixes for listing details.
1. Send a message (with PR link) to …

Start of testing, also very small quick fixes for listing details.

---

backend/ORM/index.js
backend/functions/General-Bookings-CRUD-Bookings-develop/index.js
backend/functions/PropertyHandler/index.js

quickfix password orm

---

backend/ORM/index.js
backend/package.json
backend/test/PropertyHandler/end-to-end.test.js

- Related Issue: #138 
Description: Implement test database to orm when npm test is ran (test environment variable is set in package.json test script). Also adds 1 test that uses new testing database.
As …

Implement test database.

---

frontend/web/src/styles/sass/pages/home/homePage.scss

Description: Really small change which i noticed and couldn't help but fix.
_All boxes must be checked before …

quick fixes Become a host text header inconsistent spacing 

---

backend/events/General-Bookings-CRUD-Bookings-develop/get.js
backend/functions/General-Bookings-CRUD-Bookings-develop/data/reservationRepository.js
frontend/web/src/features/hostdashboard/HostReservations.js
frontend/web/src/features/hostdashboard/services/getReservationsFromToken.js

Fun fact: This branch + Commit was made in git cli!
Description:Fixes a oversight error which occured due to migration.
_6. “Merge” your branch to the master …

fix: host dashboard backend, remove catch for invalid error catching

---

frontend/web/src/content/de.json
frontend/web/src/content/en.json
frontend/web/src/content/es.json
frontend/web/src/content/nl.json
frontend/web/src/pages/landingpage/ContactForm.jsx
frontend/web/src/pages/landingpage/FaqItem.jsx
frontend/web/src/pages/landingpage/Landing.js
frontend/web/src/services/contactService.js
frontend/web/src/styles/sass/pages/landingpage/components/_contactForm.scss
frontend/web/src/styles/sass/pages/landingpage/components/_faq.scss
frontend/web/src/styles/sass/pages/landingpage/landing.module.scss

Name: @Moncef1106 
- Closes #2058 (only if it should close it)
Description:  Added the contact form
- [ x] Big change (+-max 1000)
- [x ] New feature
As the Pull Requester, **you are responsible for your own pull request.** …

Contact form

---

frontend/web/src/pages/landingpage/ContactForm.jsx
frontend/web/src/pages/landingpage/Landing.js

Description: Fixed the input of the phone and "number of of properties" field
As the Pull Requester, **you are responsible for your own pull …

Fixed scroll to contact and input in phone and other fields

---

docs/developer_resources.md

Description: [adds developer resources page to the wiki]
As the Pull …

docs: add developer resources in /docs

---

frontend/web/src/pages/landingpage/Landing.js

landing(web): remove 'Calculate Your Rental Potential' section

---

PULL_REQUEST_TEMPLATE.md

Description: [updated checklist in PR template to include bulletpoints about P
R lengths and config files
_All …

PULL_REQUEST_TEMPLATE bulletpoints update

---

backend/events/General-Bookings-CRUD-Bookings-develop/get.js
backend/events/General-Bookings-CRUD-Bookings-develop/post.js
backend/functions/General-Bookings-CRUD-Bookings-develop/data/reservationRepository.js

Description: fixes backend code to get a valid response from request …

Backend fix getbyHostId

---

.github/.idea/.gitignore
.gitignore
backend/test/General-Bookings-CRUD-Bookings-develop/unit.test.js
frontend/web/src/App.js
frontend/web/src/pages/channelmanager/ChannelManagerCard.js
frontend/web/src/pages/channelmanager/Channelmanager.css
frontend/web/src/pages/channelmanager/Channelmanager.js
frontend/web/src/pages/channelmanager/SideDashboard.js

Name: @YusufTopal61 
- Related Issue: #440  (in the issue a reference will be added to this pr)
As the …

Channelmanager yusuf UI

---

frontend/web/src/components/base/Footer.js
frontend/web/src/components/base/Header.js
frontend/web/src/content/en.json
frontend/web/src/features/bookingengine/listingdetails/components/imageGallery.js
frontend/web/src/features/bookingengine/listingdetails/components/rating.js
frontend/web/src/pages/about/About.js
frontend/web/src/pages/home/homePage.js
frontend/web/src/pages/landingpage/Faq.js
frontend/web/src/pages/landingpage/Landing.js
frontend/web/src/pages/landingpage/store/reviews.js
frontend/web/src/pages/whydomits/Whydomits.js
frontend/web/src/styles/sass/features/base/header.scss
frontend/web/src/styles/sass/pages/landingpage/landing.module.scss

Simple quick fixes
